### ISSUE TITLE
Progress bar is not displayed

### ISSUE THREAD

**Issue by luananama** [magpie-ea/magpie3-mental-rotation#1]
When running locally, the progress bar is not shown for the KeypressScreen, even though it is in the source code.

**Comment by marcelklehr** [comment]
Hi @luananama 

Thank you for the feedback! I can confirm that the :progress prop is broken for built-in screens in the latest version. I will publish a fix shortly.

**Comment by marcelklehr** [comment]
[Using the just released version](https://github.com/magpie-ea/magpie3-mental-rotation/commit/7c5c47e8127bc4617eb6df8b1537055c63dd8d17) (v3.3.0) this should be fixed. If you stumble upon more problems, don't hesitate to open a new issue :)
